name: up-to-date

on:
  pull_request:
    branches:
      - main
      - staging
      - dev

permissions:
  contents: read

jobs:
  up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Required check
        run: echo "Placeholder so GitHub can require branches to be up to date before merge."
